# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20170525_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.CreateModel(
            name='SeriesToPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Series')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='series',
            field=models.ManyToManyField(blank=True, null=True, through='posts.SeriesToPost', to='posts.Series'),
        ),
    ]
