# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20170525_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seriestopost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='seriestopost',
            name='series',
        ),
        migrations.DeleteModel(
            name='SeriesToPost',
        ),
    ]
